"""empty message

Revision ID: 294b618d5436
Revises: 6ff76390745e
Create Date: 2025-11-29 21:49:13.019440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294b618d5436'
down_revision = '6ff76390745e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('climate', sa.String(length=30), nullable=True),
    sa.Column('surface_water', sa.String(length=30), nullable=True),
    sa.Column('diameter', sa.String(length=30), nullable=True),
    sa.Column('rotation_period', sa.String(length=30), nullable=True),
    sa.Column('terrain', sa.String(length=30), nullable=True),
    sa.Column('gravity', sa.String(length=30), nullable=True),
    sa.Column('orbital_period', sa.String(length=30), nullable=True),
    sa.Column('population', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('consumables', sa.String(length=30), nullable=True),
    sa.Column('cargo_capacity', sa.String(length=30), nullable=True),
    sa.Column('passenger', sa.String(length=30), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(length=30), nullable=True),
    sa.Column('crew', sa.String(length=30), nullable=True),
    sa.Column('length', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=30), nullable=True),
    sa.Column('manufactured', sa.String(length=30), nullable=True),
    sa.Column('vehicle_class', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_color', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('homeworld', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.alter_column('height',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('description')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('homeworld')
        batch_op.drop_column('mass')
        batch_op.drop_column('gender')
        batch_op.drop_column('skin_color')

    op.drop_table('vehicle')
    op.drop_table('planet')
    # ### end Alembic commands ###
