"""empty message

Revision ID: 3ee934d5221a
Revises: 294b618d5436
Create Date: 2025-11-29 22:04:21.159977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee934d5221a'
down_revision = '294b618d5436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_character',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)

    op.drop_table('user_character')
    # ### end Alembic commands ###
