"""empty message

Revision ID: ea3f43d5d728
Revises: 111f5d44c63b
Create Date: 2025-11-30 16:36:23.811158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3f43d5d728'
down_revision = '111f5d44c63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
